### ISSUE TITLE
Can't switch between sub-categories in the SC

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#101]
**Describe the bug**
Categories are broken in the Software Center (master) using MauiKit 2.1.0.  The UI is bugged, and clicking any sub-category does not work.

**To Reproduce**
1. Compile and install SC
2. Click on a category and then a sub-category, i.e., Internet>Browser
3. Nothing happens

**Expected behavior**
Switch to the sub-category.

**Screenshots**
![image](https://user-images.githubusercontent.com/3053525/145730283-86145bf3-3cb8-49b7-9dec-ff57cf7b4ad0.png)

**Comment by probal31** [comment]
@UriHerrera Have submitted some fix for the mentioned issue. 
Here is the link to the pull request: https://github.com/Nitrux/nx-software-center/pull/103

Can you please check if this solves the issue you mentioned?

**Comment by UriHerrera** [comment]
@probal31 yes it fixes it
