### ISSUE TITLE
Add support for downloading AppImages from https://apprepo.de/

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#105]
> Apprepo is a non-profit volunteer project inspired by the Linux App Store online services like snapcraft.io or flatpak.org. With this project, I am trying to prove the concept of a distro-agnostic package manager and application store for Linux systems. 

_From [What is AppRepo?](https://apprepo.de/page/about)._

The website has 252 AppImages to date.

The developer has a GitHub organization here https://github.com/area-of-dev.

**Comment by probal31** [comment]
Here is the api doc: https://apprepo.de/api/doc

The list of packages is available via this rest api: https://apprepo.de/rest/api/package/?format=json
