### ISSUE TITLE
NX Software Center AppImage does not run in Fedora 35

### ISSUE THREAD

**Issue by toni-schmitt** [Nitrux/nx-software-center#112]
**Describe the bug**
AppImage does not run from Terminal (`./nx-software-center-latest-x86_64_1ecc2d976c02d41c43ad757b3b2ab89b.AppImage`), from Applications Menu (integrated trough AppImageLauncher) or only running trough AppImageLauncher

**Error Message**
```
/tmp/.mount_nx-sofbsa8nz//usr/bin/nx-software-center: /lib64/libcurl.so.4: no version information available (required by /tmp/.mount_nx-sofbsa8nz//usr/lib/x86_64-linux-gnu/libappimageupdate.so)
/tmp/.mount_nx-sofbsa8nz//usr/bin/nx-software-center: symbol lookup error: /lib64/libssh.so.4: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
```

**Screenshots**
First two Error Messages in the following screenshots are from AppImageLauncher (as seen here)
![image](https://user-images.githubusercontent.com/25370820/164164080-5a7920b1-30ca-4176-b316-88302b1e0716.png)
1. Run only (no integration)
![image](https://user-images.githubusercontent.com/25370820/164164165-e758cd29-32ba-40f0-86e5-e58add1cdb40.png)
2. Run and integrate
![image](https://user-images.githubusercontent.com/25370820/164164209-573fa646-a72a-4d1d-8ab0-45cc8b4e1788.png)
3. Execute from integarted place (~/Applications)
![image](https://user-images.githubusercontent.com/25370820/164164377-8202a671-2e54-4f9a-a04f-00f211de796f.png)

**Desktop:**
 - OS: Fedora Workstation 35 (64 bit)

**Comment by UriHerrera** [comment]
![VirtualBox_Fedora_25_06_2023_09_53_17](https://github.com/Nitrux/nx-software-center/assets/3053525/31fea335-0865-41ab-9701-62428b124d89)

The latest AppImage works in Fedora 38.
