### ISSUE TITLE
Results from AppRepo sometimes don't show up

### ISSUE THREAD

**Issue by laniusone** [Nitrux/nx-software-center#114]
**Describe the bug**
From time to time, the app results are served from AppImageHub only, sometimes there are results from both repositories, there is no clear reason why is it like that.

**To Reproduce**
1. Search for something, e.g. Emacs (it is available in AppRepo and not on AppImageHub)
2. There are no results, also the loader is spinning constantly with no message.

**Expected behavior**
Results from AppRepo would be visible as well, or there would some meaningful message or indication why AppRepo results are not loaded, or that there is nothing found.

**Desktop**
 - OS: Nitrux
 - Version: 2.2.0 build.310522 x86_64

**Comment by UriHerrera** [comment]
Please run the Software Center from the terminal and add the output to your issue. I can't reproduce this issue as is.

If I perform a search, I get results every time. Maybe it was a problem with the AppRepo server serving the files or the API; we don't have control over it either.

Regarding displaying a message if NX Software Center found no result, yes, that's missing.

**Comment by UriHerrera** [comment]
AppRepo support is now removed; see #129
