### ISSUE TITLE
AppImage fails to run on Debian 10.13

### ISSUE THREAD

**Issue by mrix69** [Nitrux/nx-software-center#125]
When running the application in Debian 10.13, it ends with an error.

**To Reproduce**
1. run terminal
2. execute `./nx-software-center-latest-x86_64.AppImage`
3. See the error 

```
/tmp/.mount_nx-sofAscyg8/usr/bin/nx-software-center: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_nx-sofAscyg8/usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5)
```

4. to repeat the error

**Desktop (please complete the following information):**
 - OS: Debian 10.13

**Comment by UriHerrera** [comment]
@mrix69 Please run the following command(s) and add the output (also, please format the output properly)

```
lsb_release -a
apt-cache policy libstdc++6 libc6
strings /lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC
env | grep 'DESKTOP_SESSION\|XDG_SESSION_DESKTOP\|XDG_SESSION_TYPE'
```

Thanks.
