### ISSUE TITLE
NX SC AppImage is missing libraries

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#127]
**Describe the bug**
The AppImage fails to launch due to it missing `libappimageupdate.so` and `libappimage.so.1.0abi1`. It also includes `libappimage.so.1.0.3`, which will not work.

**Comment by probal31** [comment]
@UriHerrera Can you please check the latest AppImage from the release now? 

Thanks.

**Comment by UriHerrera** [comment]
It runs but it doesn't download anything.

Clicking the categories doesn't do anything. Here's the output when I click any category on the sidebar.

```
qrc:/ui/views/store/StoreFrontPage.qml:87: TypeError: Cannot read property 'hasTransientTouchInput' of undefined
qrc:/ui/views/store/StoreFrontPage.qml:87: TypeError: Cannot read property 'hasTransientTouchInput' of undefined
qrc:/ui/views/store/StoreFrontPage.qml:87: TypeError: Cannot read property 'hasTransientTouchInput' of undefined
qrc:/ui/views/store/StoreFrontPage.qml:87: TypeError: Cannot read property 'hasTransientTouchInput' of undefined
```

Clicking a file to download also doesn't work. Here's the output when I click a file to download.

```
qrc:/maui/kit/GalleryRollTemplate.qml:114:17: QML Image: Error transferring https://images.pling.com/cache/770x540-0/img/00/00/51/22/62/1355468/69aa04770877a7a345fcc1337139597bca17f1073 - server replied: Not Found
```

Search kind of works, it shows results but not from both sources.

Downloading files from AppRepo doesn't work. Here's the output.

```
qrc:/maui/kit/IconItem.qml:111:5: QML Image: Error transferring https://apprepo.de/medias/package/icon/2023/02/13/213525/wpsoffice.svg - server replied: Bad Gateway
qrc:/ui/templates/AppPage.qml:376:29: QML Image: Error transferring https://apprepo.de/medias/package/image/2020/04/14/205542/wps2.png - server replied: Bad Gateway
```

**Comment by probal31** [comment]
@UriHerrera Can we now close this issue if there is no issue with the latest release?
