### ISSUE TITLE
Clicking "Remove" when highlighting an AppImage does not delete it

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#134]
Clicking the button "Remove" when the cursor hovers over an entry in the Apps view does not result in the deletion of the file; instead, a dialog appears. However, even clicking "Close" does not do any action.

![photo_2023-10-03_19-08-24](https://github.com/Nitrux/nx-software-center/assets/3053525/4fabb7f3-73ce-4ad9-beee-d6566fb4da96)

**Comment by probal31** [comment]
Hello @UriHerrera,

The issue has been fixed and is available in the latest release AppImage:
[nx-software-center-latest-x86_64.AppImage](https://github.com/Nitrux/nx-software-center/releases/download/latest/nx-software-center-latest-x86_64.AppImage)

Requesting you to please check and confirm.

Thanks.

**Comment by UriHerrera** [comment]
I can't check it due to the latest available AppImage not working see #137

**Comment by probal31** [comment]
> I can't check it due to the latest available AppImage not working see #137 

@UriHerrera can you please check this now with the latest appimage?

**Comment by UriHerrera** [comment]
Yes, that works too.

> > I can't check it due to the latest available AppImage not working see #137
> 
> @UriHerrera can you please check this now with the latest appimage?
