### ISSUE TITLE
New UI Design

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#14]
This is the redesign of the NX Software Center. Last month we made the decision to remove support for Snaps from the software center which meant that the UI that was in use was scrapped. This presented an opportunity to redesign the software center.

Here are the UI mockups:

Home
===

This is where the user manages the AppImages that are present ("installed") in the system. On the left pane there's a list of categories where AppImages are organized. Selecting each category filters the AppImages that match the criteria. To the right of the category label there's a counter that lists how many AppImages fall under that category. And below that there's a dropdown that sorts AppImages by: Size, Date of installation and Name.

1- This is what the user would see when there are no AppImages present ("installed") in the system. At the top there's a message box notifying the user that no AppImages were found.
![](https://i.imgur.com/sF3s7UX.png)
2- This is what the user would see after downloading some AppImages but not using any category filter. The software center would default to display all AppImages.
![](https://i.imgur.com/wx4Emdi.png)
3- This is how the filtering of the AppImages works. Only the AppImages that correspond to the "Development" category are visible with other AppImages hidden from the view.
![](https://i.imgur.com/0bRms7F.png)
4- This detailed view is what the user would see upon clicking on an AppImage that is present ("installed") in the system. At the top there's a non-interactive breadcrumb-like navigation title, a banner (that pulls an image related to the software from Google) with an overlay the same color as the window background at 90% opacity, the icon (pulled from the system-wide icon theme), the _real_ name of the app and the developer. Below a button to "remove" the AppImage or "open/run" the AppImage. If it's not possible to fetch the developer name/handle use the source from where the AppImage was downloaded from as a replacement. Below is the information of the software providing: website URL, version and size and finally the software description (pulled from Wikipedia if available otherwise pulled from the AppImage source or the AppImage description). Next to this a carousel gallery with images pulled from Google. And at the bottom-left of the window a "go back" button to return to the previous view, whether that's the Search or the category listing.
![](https://i.imgur.com/gCy6vwU.png)

Search
===

This is where the user searches for new and /or existing AppImages. Search is global, results appear from local and/or available AppImages from the selected source.

1- This is what the user would see when no results are found.
![](https://i.imgur.com/lEVjZw5.png)
2-  This is what the user would see when the search returns a result but the are no AppImages present ("installed") in the system that match the criteria.
![](https://i.imgur.com/I9m9D61.png)
3- This is what the user would see when the search returns a result and there are AppImages present ("installed") in the system that match the criteria.
![](https://i.imgur.com/MCT63UW.png)
4- Clicking on an AppImage from the search results would take the user to a different detailed view depending on whether the AppImage is present ("installed") in the system or not.

Store
===

The main Store component. 

1- This is what the user would see as the main Store. At the top is a banner that features a _randomized carousel of 5 applications_  (that pulls an image related to the software from Google), the icon (pulled from the system-wide icon theme), the _real_ name of the app and version with a "Get it now!" call-to-action message. Clicking this banner would take the user to the AppImage detailed view. Below are the categories as made available by the selected source from where the software center is fetching the AppImages. Below this are AppImages that are listed as "Popular", these are AppImages with the larger download numbers in descending order. And below are "New" AppImages which are AppImages that were recently added to the source from where the software centers is fetching the AppImages.
![](https://i.imgur.com/tAu6VQY.png)
2- This detailed view is what the user would see upon clicking on an AppImage that isn't present ("installed") in the system. At the top there's a non-interactive breadcrumb-like navigation title, a banner (that pulls an image related to the software from Google) with an overlay the same color as the window background at 90% opacity, the icon (pulled from the system-wide icon theme), the _real_ name of the app and the developer. Below a button to "download" the AppImage. If it's not possible to fetch the developer name/handle use the source from where the AppImage was downloaded from as a replacement. Below is the information of the software providing: website URL, version and size and finally the software description (pulled from Wikipedia if available otherwise pulled from the AppImage source or the AppImage description). Next to this a carousel gallery with images pulled from Google. And at the bottom-left of the window a "go back" button to return to the previous view, whether that's the main Store or the category listing.
![](https://i.imgur.com/g90q4nZ.png)
3- This is what the user would see when clicking on a category from the main Store and no AppImages are present ("installed") in the system. AppImages are not displayed in any particular order.
![](https://i.imgur.com/OrKbAy6.png)
4- This is what the user would see when clicking on a category from the main Store and AppImages are present ("installed") in the system and the apps come match the Store category.
![](https://i.imgur.com/OrKbAy6.png)
5- This is what the user would see as the main Store if the selected source doesn't provide AppImages that match the criteria of the categories, in other words if the source from where the software center is fetching the AppImages doesn't have files under the category "Development" the category is greyed-out and can't be clicked. Below this are AppImages that are listed as "Popular", these are AppImages with the larger download numbers in descending order. And below are "New" AppImages which are AppImages that were recently added to the source from where the software centers is fetching the AppImages.
![](https://i.imgur.com/TxbjEyJ.png)
6- This is what the user would see when clicking on "New" or "Popular" and there are not apps present ("installed") in the system.
![](https://i.imgur.com/jJbGPwF.png)
![](https://i.imgur.com/PcOOnLA.png)
7- This is what the user would see when clicking on "New" or "Popular" and there are apps present ("installed") in the system.
![](https://i.imgur.com/NpViOHy.png)
![](https://i.imgur.com/QL0laXY.png)

Download Queue
===

This is where the AppImages are added to be downloaded by the user. Clicking download from the Store adds the AppImage to this list and are downloaded.

1- This is what the user would see after adding AppImages to the queue. The list displays the file name, download size, version and progress. At the bottom a status bar tells the user the status of the download and at the rightmost side of the window there's a button to initiate the download, this button changes from "Download" to "Downloading" once the user starts the process. The process would trigger a notification that it's begun downloading the file(s).
![](https://i.imgur.com/vQP7aJN.png)
2- This what the user would see if the download presents a problem. The software center would be displaying an error message. In this case the button changes to "Retry" to restart the download process. An unsuccessful download would trigger a notification.
![](https://i.imgur.com/mLA0jFb.png) 
3- This is what the user would see once the download was successful. The button changes from "Downloading" to "Clear" to clear up the list. A successful download would trigger a notification.
![](https://i.imgur.com/JsFBAmb.png)

Settings
===

The settings of the software center.

1- This is what the user would see when clicking the settings button. The settings list is minimal: First is the option to choose what source does the software center uses to fetch AppImages. AppImage Hub is set by default and opendesktop.org is available as an option. Additionally the user could type a specific URL if there are other AppImage sources available. Below that the is option to set a proxy. And then is the option to specify where the AppImages are downloaded to.
![](https://i.imgur.com/EETOt4E.png)

----

Other
===

- Removing AppImages only generates a notification that the file was removed.
- Update method is pending. AppImageUpdate provides the mechanism for updating AppImages but should the software center have this feature or should it be a separate application?.
- I used a text edit box in the settings where the user can specify the download location however a drop down with locations that `appimaged` supports is an alternative. The drop down could also replace both the radio button and the text edit.

===

I don't know why imgur keeps deleting the previews so here's the album where they are: https://imgur.com/a/Ltfkd

**Comment by star-buck** [comment]
looks nice!
Would supporting appstream_id make things look instantly nicer?
Like people who create an appimage could embed the appstream_id and nx software center could display nice images and description?
