### ISSUE TITLE
Download progress indicator

### ISSUE THREAD

**Issue by probonopd** [Nitrux/nx-software-center#23]
Download progress indicator is missing.

It used to be there:

![](https://user-images.githubusercontent.com/2480569/33243768-497bf74a-d2ba-11e7-8336-ae2018229e57.gif)

**Comment by azubieta** [comment]
We moved the download progress notifications away to another page but yes it could be a nice addition. But in what GUI refers I'll left the final word to @UriHerrera

**Comment by star-buck** [comment]
I kinda liked the "Get" Button more, as it includes the meaning of downloading and also placing it somewhere aka "installing"...

**Comment by probonopd** [comment]
Yes, I like "Get" too. Much better than "Install", possibly also better than "Download".

**Comment by star-buck** [comment]
Get & Run, both short ;)

**Comment by probonopd** [comment]
Remember those times?

![](https://www.linux-user.de/ausgabe/2003/09/044-lindows/clicknrun.png)

**Comment by UriHerrera** [comment]
You mean this?:

![](https://i.imgur.com/3OUqSid.png)

**Comment by azubieta** [comment]
What i plan to do is to append an small badge with a counter of the running task or available updates to the ¨Tasks button¨.

So when you start a download you will get a visual notification that the details are in that page.
Aslo we can make that if you click the ¨download started¨ notification message it took you to the tasks view.
