### ISSUE TITLE
Display application icon after the AppImage has been downloaded

### ISSUE THREAD

**Issue by probonopd** [Nitrux/nx-software-center#41]
These look sooo much better ;-)

![icons](https://user-images.githubusercontent.com/2480569/37259007-5eddd25a-2578-11e8-971a-286fd7ea2ead.png)

So one could display the icons from the thumbnailer...  after the AppImage has been downloaded. Would also give a immediate visual distinction between apps that still need to be downloaded and those that are already downloaded.

**Comment by azubieta** [comment]
If you tried the latest release you'll find that some apps now have icons.
We are getting those from appimagehub.com
It would be nice not only for the installed apps but for all apps to have
those icons. So what do you say if we opload them to appimage hub.org as
well ?

**Comment by probonopd** [comment]
Yes, for that https://github.com/AppImage/appimage.github.io/issues/427 needs to be implemented; should be not too complicated. PR welcome :-)
