### ISSUE TITLE
Port UI to qqc2 and use Nomad HIG

### ISSUE THREAD

**Issue by milohr** [Nitrux/nx-software-center#44]
Port the UI from using Plasma components to Kirigami ones and use the Nomad HIG

**Comment by milohr** [comment]
This is what the Toolbar looks like right now.
I'll make that initial pull request, since it implies changes like moving from QGuiApplication to QApplication and other minor things.

![screenshot_20180401_123240](https://user-images.githubusercontent.com/5911329/38101368-c18dec20-3345-11e8-942d-417563fe2e5e.png)

**Comment by azubieta** [comment]
I would like to keep it all in a separated branch until every plasma
frameworks component get replaced.

**Comment by UriHerrera** [comment]
https://github.com/milohr/nx-software-center/tree/development

WIP

![image](https://user-images.githubusercontent.com/3053525/46598544-10359c00-caaa-11e8-985e-200ff5040db9.png)
