### ISSUE TITLE
Improve AppImage Listings retrieval

### ISSUE THREAD

**Issue by azubieta** [Nitrux/nx-software-center#52]
Currently the nx-software-center fetch the whole applications listings at the start of the application which is too slow (varies depending on the internet connection) because in the case of the AppImages coming from https://appimage.github.io/ there are no direct download links but the link to the official developer download page (most of cases github releases) so we must scrap those pages also.
Luckily this doesn't happen with https://www.appimagehub.com/ for two reasons because the download links are included and because the listing are still small.

I'm considering the following options to reduce the download times:

1. Create a cache and do the cache updates in the background. It will only take longer the first time the app is opened, but all the listings will be fetched every time. Once the listings grow (as big as the current Debian or Ubuntu repositories) they will consume more then 50mb the equivalent of downloading a whole AppImage file.

2. Only fetch the "featured" applications and the ones matching the user queries. This method implies making an HTTP request every time the user introduces a new query but as the response will be small (no more than 30 apps or ~3KiB) it will be fast even in slow connections. This method will require a dynamic response from listings servers which is not currently supported by https://appimage.github.io/. 

I prefer option two because it scales better when the number of AppImages available grows. But the static design of appimage.github.io is a limitation. As an alternative I was considering to create a new web service to store and provide an unified listing from both sources. 

But I before doing anything I would like to hear your thoughts about it @probonopd @star-buck

**Comment by probonopd** [comment]
I see two main strategies around this.

1. In certain intervals, e.g., once per hour, get the feed from https://appimage.github.io/feed.json using a cron job on a server and get the version information from the upstream sites; then output another feed which is in turn consumed by the clients; or
2. When launching the client, _only_ show information that is contained in https://appimage.github.io/feed.json and only one the user clicks on a certain application, start fetching the version information (and other advanced metadata) _for that application_

**Comment by azubieta** [comment]
I just started the [nx-software-center-server](https://github.com/nomad-desktop/nx-software-center-      server/)  it will provide a JSON formated web API of the AppImage listings. It will be feed by scrappers from appimagehub.com and and appimage.github.io and also manually for special cases.
