### ISSUE TITLE
Redesign using MauiKit HIG

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#62]
# Introduction

The code that is in this repository makes use of Plasma UI components to draw the interface of the application. At the time, this was the right solution as it provided an easy way to integrate the program with the system.

MauiKit now exists, and with it, we can create a new program that works in the desktop and mobile.

The Software Center was initially conceived to serve Snap applications and consequently AppImages. AppImages weren't downloaded from a central repository, but the user managed them with the SC merely listing them. _Additionally, the SC was not designed to handle system updates._

Eventually, it was observed that [linuxapps.com](linuxapps.com) provided an API that we could use to serve Appimages from a central source, and as such, this was used as the backend of the SC.

linuxapps.com was deprecated, and its lack of AppImages was a problem, we figured that we needed a way to obtain AppImages directly from their GitHub release pages as this was a more straightforward and more accessible way always to have the latest available.

[AppImagehub.com](https://appimagehub.com) provided a new central repository for AppImage files and a revised [API](https://github.com/KDE/ocs-webserver) by openDesktop that offers more modern functionality too. Therefore, in this redesign, it's proposed to make use of it.

# Functionality

The way that these new design works are made to be simple — both in how the user interacts with it and how the program delivers the requests to the user.

The following issues already cover many of the core concepts, to not go all over them again; I'll refer them here.

- [UI Design #45](https://github.com/Nitrux/nx-software-center/issues/45)
- [New UI Design #14](https://github.com/Nitrux/nx-software-center/issues/14)

The redesign of the SC also takes into account more than just Software, for instance, artwork such as themes, wallpapers, and icons. Ergo, the SC can be viewed as more of a *Content* storefront than just a software manager.

### Differences with the current SC code

1. This redesign of the SC takes into consideration the added functionality of integrating system updates serving as a GUI to [znx](github.com/Nitrux/znx). As a reference, check [znx-gui](github.com/Nitrux/znx-gui)
2. AppImages are downloaded from [AppImagehub.com](https://appimagehub.com) and stored in `/home/$USER/Applications`. The SC can perform the queries to the site by using [AppImage CLI Tool](https://www.opencode.net/azubieta/appimage-cli-tool) as its backend instead of building this feature in the main program.
3. No integration of AppImages with the desktop environment is done by the SC itself, [appimaged](github.com/AppimageKit/appimaged) fulfills this purpose.
4. Not all Appimages are built equal, that is to say, that as the point above, the SC shouldn't perform the update by itself but rather make use of [AppImageUpdate](github.com/AppImageKit/AppImageUpdate) which fulfills this purpose. However, regardless of this, if the developer or the person that created the AppImage did not include the update information, the AppImage will not be updatable and will have to be downloaded again to overwrite the existing version.

## Notes

1. For content that is not an AppImage, the SC will make use of the standard paths. The SC will download, extract, and move the resulting folder to the following paths:
 - For GTK:
     - `~/.themes/` " For GTK2 | GTK3 themes."
     - `~/.icons/` "Icon themes."
 - For Plasma:
     -  `~/.local/share/color-schemes/` "Color-schemes."
     -  `~/.local/share/icons/` "Icon themes."
     - `~/.local/share/plasma/desktoptheme/` "Plasma themes."
     - `~/.local/share/plasma/plasmoids/` "Plasmoids."
     - `~/.local/share/aurorae/themes/` "Aurorae window decorations."
     - `~/.local/share/kwin/effects/` "KWin effects."
     - `~/.local/share/kwin/scripts/` "KWin scripts."
 - For both
     - `~/.icons/` "Cursor themes."

## Requirements

1. The SC should be distributed as an AppImage meaning that it should pack everything to make it work, including the above tools.
2. SC should use [MauiKit](https://invent.kde.org/kde/mauikit).
3. SC should be easy to maintain.
4. SC should use the [API](https://github.com/KDE/ocs-webserver) by openDesktop.

## Content Workflow

The workflow is the following:

1. The user clicks the SC icon on the application menu.

2. The user is shown the SC window, by default the "Store" view is displayed.
![image](https://user-images.githubusercontent.com/3053525/60152555-8ac45a00-97a6-11e9-8010-047c90a861de.png)
      - In this view, the user is presented with a featured item from [openDesktop.org](https://www.opendesktop.org/) and a list of items available to download. Similarly presented as the website —  _See fig.1_.
![image](https://user-images.githubusercontent.com/3053525/60152806-ba279680-97a7-11e9-88fc-a8f4712594f4.png)
      - Accordingly, a list of categories is always visible on the left sidebar of the window.
![image](https://user-images.githubusercontent.com/3053525/60152859-f955e780-97a7-11e9-9476-09c643ed0781.png)
     - To download new content
     - At the bottom, a pager is displayed to navigate more content — _See fig.2 and 3_.
![image](https://user-images.githubusercontent.com/3053525/60153222-3e2e4e00-97a9-11e9-8855-e2e6b6be6cca.png)

3. Switching to the "Apps" view allows the user to see the AppImages that are currently in the system.
![image](https://user-images.githubusercontent.com/3053525/60152077-c5c58e00-97a4-11e9-973c-6f4ab15821f9.png)
   - AppImages are displayed utilizing a "cards widget from MauiKit." — _See fig.5_.
   - In this view, the user can "Run," "Update," or "Remove/Delete" an AppImage.
![image](https://user-images.githubusercontent.com/3053525/60152188-2c4aac00-97a5-11e9-9bcc-d938b77f5d83.png)
   - AppImages displayed here are sorted by recently added by default. The user has the option to sort them differently.
   - Removing an AppImage deletes the AppImage file from the system and displays a notification after completion — _See fig.6_.

4. Pressing the queue button takes the user to the "Queue" view.
![image](https://user-images.githubusercontent.com/3053525/60151759-9eba8c80-97a3-11e9-8380-1fb81aaba66f.png). 
    - The button will display two options:
![image](https://user-images.githubusercontent.com/3053525/60152029-9c0c6700-97a4-11e9-91ae-1ce96835cd21.png)
![image](https://user-images.githubusercontent.com/3053525/60152015-8dbe4b00-97a4-11e9-96a1-4314d5dcb5c7.png)
      - Clicking the left icon will show the "Download Queue" where the user can monitor downloaded AppImages —  _See fig.11_.
      - Clicking on the right image will show the "Update Queue," where the user can watch updates —  _See fig.12_.
      - If there's a problem downloading or updating the AppImage, a warning icon is used — _See fig.7 and 8_.
![image](https://user-images.githubusercontent.com/3053525/60152364-d32f4800-97a5-11e9-8b8c-0517a9e74db0.png)

5. Clicking the hamburger menu displays the "Account" menu. This menu allows the user to manage the addition or deletion of accounts, the settings of the program, and an about dialog — _See fig.2_.
![image](https://user-images.githubusercontent.com/3053525/60153461-ed6b2500-97a9-11e9-896b-4ff31e062984.png)

6. Available AppImages are ordered in categories — _See fig.2 and 3_.

7. Clicking on the content icon (application or artwork) displays more information about the item, we'll call this view "Item" view — _See fig.2 and 3_.
      -  At the top-left of the window, new options are displayed. These are "Favorite," "Pling," and "Product Gallery."
![image](https://user-images.githubusercontent.com/3053525/60153599-636f8c00-97aa-11e9-8222-89d039dba5d9.png)
      - The information for the fields "Description," "Details," and "Changelog" are borrowed using the API.
      - More options are provided in the _kebab_ menu.
![image](https://user-images.githubusercontent.com/3053525/60153896-52734a80-97ab-11e9-9762-4816e7cec16c.png)
      - If the application has more than one file available to download a dropdown indicator is used to select which file to download — _See fig.5_.
      - At the top of the "Item" view, the application or the available _product_ icon used in openDesktop is used, below this, the name of the item, author and the size of the item.
      - In the background, an image from the product gallery is used, blurred and with an overlay of the color of the window background `#fafafa` with 70% opacity.

## System Management Workflow

As mentioned at the beginning, the SC will serve as the main GUI for znx. We're currently using znx-gui for this purpose, which while it works, it's not particularly informative and gives the impression that znx is a complicated tool to utilize, which it isn't.

The functions of znx can be displayed in one unified view which denotes the simplicity of the program, and the workflow is the following:

1. The user switches to the "System" view.
![image](https://user-images.githubusercontent.com/3053525/60156510-535baa80-97b2-11e9-8287-ecb42a2a9d65.png)

2. For znx to start using a device, it must initialize it — _See fig.17_.
    - After znx successfully initializes the available storage device, the SC will display a notification — _See fig.18_.
    - An additional button allows the user to "Restore the ESP."

3. To deploy a new image, the user will click the button labeled "Deploy" which will open a file dialog, after selecting the image the user will proceed to input a name in a window similar to this.
![image](https://user-images.githubusercontent.com/3053525/60156816-f14f7500-97b2-11e9-8f0b-6a7c364e91c4.png)
    - After znx successfully deploys an image to the storage device, it will display a notification.

4. The deployed images are listed in the same other content is listed in the SC window — _See fig.19 and 20_.
    - The user is now able to either "Remove," "Update," "Revert,"  or "Reset," and image.
    - After each successful action, a notification is displayed.

In the same fashion that AppimageUpdate, appimaged, and AppImage CLI Tool provide the necessary functionality, znx offers all the required functions which the SC only needs to call.

## Mobile

The mobile iteration works the same way, with the difference that the sidebar is always in compact mode.  — _See fig.21 and 22_.

# UI Mockup

![sc](https://user-images.githubusercontent.com/3053525/60148848-46ca5880-9798-11e9-8283-36f34e7bbaab.png)

> Nitrux Desktop Store, a digital distribution platform for computer software.

**Comment by lokize** [comment]
Nice, waiting for this!

**Comment by UriHerrera** [comment]
# Progress

### Desktop

![70235268_2382888195128504_4155690345633415168_o](https://user-images.githubusercontent.com/3053525/65631085-6857fd80-df9c-11e9-998e-f8ec49b88d0e.jpg)
![70466057_2382888188461838_2409339222692462592_o](https://user-images.githubusercontent.com/3053525/65631086-68f09400-df9c-11e9-9cd7-3081723171b5.jpg)
![70579132_2382888375128486_2841943618829156352_o](https://user-images.githubusercontent.com/3053525/65631087-68f09400-df9c-11e9-9934-881bc489ca05.jpg)
![70579816_2382888201795170_7479113434865336320_o](https://user-images.githubusercontent.com/3053525/65631088-68f09400-df9c-11e9-948e-3d0f993ca46a.jpg)

### Mobile

![70366678_2396192397131417_2172701814766436352_o](https://user-images.githubusercontent.com/3053525/65631104-74dc5600-df9c-11e9-9961-4ae45acaf34f.jpg)
![71101996_2396192387131418_5020658374925090816_o](https://user-images.githubusercontent.com/3053525/65631106-74dc5600-df9c-11e9-834d-facbe649dafc.jpg)
![70803923_2396192430464747_6664160175181529088_o](https://user-images.githubusercontent.com/3053525/65631107-74dc5600-df9c-11e9-9f1b-a7356bbe896e.jpg)

**Comment by UriHerrera** [comment]
# Progress no.2

The software center can list content from Pling.com.

![EKbWAExWwAAvsk6](https://user-images.githubusercontent.com/3053525/69782672-526ee080-1177-11ea-8a80-0336fc8b3082.jpeg)

**Comment by UriHerrera** [comment]
# Progress no.3

The _Featured_ banner works and displays the content from Pling.com. And, also how the program looks like in Breeze colors.

![photo4934053946155182195](https://user-images.githubusercontent.com/3053525/72801711-b8279800-3c0f-11ea-904c-37f275c5ac1f.jpg)

**Comment by milohr** [comment]
### **Progress no.4**

The store front page has been revamped with sections to highlight:

- highest rated
- newest
- most downloaded.

With more eye catching card delegates.

The category navigation is now "stack-page" based. So the users goes from category into subcategories by stacking pages upon the other.

The Category view was also revamped to also highlight the most recent and highest rated packages within the category, and also a subcategories navigation was added. 

The data models were updated to support the changes above. 

The installed packages view now displays the correct information. And overall all the delegates were fixed and improved.

There is still work in progress but the most major parts have been implemented. A stable release is planned by the end of November of 2020.

The UI has been also optimized to be used on the PinePhone with ARM64

**Desktop:** 

![Screenshot_20201113_155829](https://user-images.githubusercontent.com/5911329/99120975-c80ecf00-25c9-11eb-8712-7a7c14d3b928.png)

![Screenshot_20201113_155848](https://user-images.githubusercontent.com/5911329/99121017-dc52cc00-25c9-11eb-98f3-c0bc810c0566.png)

![Screenshot_20201113_155903](https://user-images.githubusercontent.com/5911329/99121034-e5439d80-25c9-11eb-9c52-c01a30457d66.png)

![Screenshot_20201113_155921](https://user-images.githubusercontent.com/5911329/99121041-e7a5f780-25c9-11eb-8641-727010f4d5dc.png)

![Screenshot_20201113_155931](https://user-images.githubusercontent.com/5911329/99121044-e96fbb00-25c9-11eb-87f1-b8707fa97f1f.png)

![Screenshot_20201113_155957](https://user-images.githubusercontent.com/5911329/99121056-ed034200-25c9-11eb-9703-2e221d5d4b80.png)

![Screenshot_20201113_155855](https://user-images.githubusercontent.com/5911329/99121024-df4dbc80-25c9-11eb-8aea-bd12f64eaf52.png)

**Phone**
![Screenshot_20201113_154944](https://user-images.githubusercontent.com/5911329/99121083-f9879a80-25c9-11eb-94f8-6059bbedb385.png)

![Screenshot_20201113_155056](https://user-images.githubusercontent.com/5911329/99121114-04422f80-25ca-11eb-943d-1ca1e55c6233.png)

![Screenshot_20201113_155022](https://user-images.githubusercontent.com/5911329/99121104-00161200-25ca-11eb-905d-16dee0281e7d.png)

![Screenshot_20201113_155004](https://user-images.githubusercontent.com/5911329/99121092-fbe9f480-25c9-11eb-8393-805564d87713.png)

**Comment by milohr** [comment]
https://github.com/Nitrux/nx-software-center/commit/d8346627c50de582ed2569a6bed8ff39f3a7e1dd

**Comment by hcsubser** [comment]
why was this closed this seemed so close to being done

**Comment by UriHerrera** [comment]
> why was this closed this seemed so close to being done

@hcsubser Because it is already done.
