### ISSUE TITLE
Downloads are very outdated

### ISSUE THREAD

**Issue by probonopd** [Nitrux/nx-software-center#63]
https://github.com/Nitrux/nx-software-center/releases is very outdated. It would be nice to have the latest continuous builds of the AppImage there. Check out linuxdeployqt or https://github.com/linuxdeploy/linuxdeploy-plugin-qt

**Comment by probonopd** [comment]
Continuous builds are failing:

```
E: Unable to locate package nomad-plasma-look-and-feel
E: Unable to locate package luv-icon-theme
E: Unable to locate package nomad-desktop-settings
E: Unable to locate package libappimage-dev
```

**Comment by UriHerrera** [comment]
Closing due to new code being developed. See https://github.com/Nitrux/nx-software-center/issues/62.

**Comment by UriHerrera** [comment]
Reopening due to new activity at the branch [dev-mauikit](https://github.com/Nitrux/nx-software-center/tree/dev-mauikit-ui)

**Comment by probonopd** [comment]
Hello, is there any chance we could get up-to-date AppImages of this application @azubieta? Or am I just looking in the wrong place? Thanks.

**Comment by UriHerrera** [comment]
There's now an updated AppImage in the [Releases](https://github.com/Nitrux/nx-software-center/releases) tab.

**Comment by probonopd** [comment]
Thanks a lot @UriHerrera. I didn't have a detailed look yet but I am surprised about its size - 181 MB. What is going on?

**Comment by star-buck** [comment]
That does sound huge indeed.

**Comment by UriHerrera** [comment]
> Thanks a lot @UriHerrera. I didn't have a detailed look yet but I am surprised about its size - 181 MB. What is going on?

According to the [build log](https://github.com/Nitrux/nx-software-center/runs/3632700224?check_suite_focus=true#step:7:3757), when appimage-builder is run the list of dependencies specified [here](https://github.com/Nitrux/nx-software-center/blob/master/nx-software-center-appimage.yml) is used. And, there's a lot of packages that are pulled that shouldn't be needed.

appimage-builder allows to exclude unwanted packages so it'd be a good idea to add many of those packages to this list. That way, the AppImage should be smaller.

**Comment by probonopd** [comment]
And even within the needed packages, maybe not all files are needed (e.g., icon sets).

**Comment by star-buck** [comment]
So who can build a new one with reduced packages?

**Comment by UriHerrera** [comment]
> So who can build a new one with reduced packages?

Yes, that's possible.

**Comment by star-buck** [comment]
But who does it? :)
