### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [Nitrux/nx-software-center#64]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/Nitrux/nx-software-center/blob/5f55d88c4e5a1007566e6fdd37f96b75423873a3/src/main.cpp#L49 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](https://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by UriHerrera** [comment]
Closing due to new code being produced. See https://github.com/Nitrux/nx-software-center/issues/62.
