### ISSUE TITLE
.deb Package Install

### ISSUE THREAD

**Issue by ghbjklhv** [Nitrux/nx-software-center#66]
**Feature**: Create [.deb](https://www.wikipedia.org/wiki/Deb_(file_format)) package for easy install for `apt` supported OSes.

**Comment by luis-lavaire** [comment]
We provide an AppImage for this application: https://github.com/Nitrux/nx-software-center/releases/download/continuous/Software_Center-x86_64.AppImage.

That's our preferred method for distributing the software center.

**Comment by UriHerrera** [comment]
The AppImage file works on all Linux distributions. As such, there's no need for distribution specific packages.

Do note however that the Software Center hasn't been updated.

**Comment by mikewesten** [comment]
Appimage is fine, initially. It's still early. 
However it's missing darkmode (or I missed a step along the way).
