### ISSUE TITLE
Is this fully FLOSS?

### ISSUE THREAD

**Issue by qhfasd** [Nitrux/nx-software-center#69]
**Question**: Is this fully FLOSS? Or is there a non-free backend or something?

**Comment by UriHerrera** [comment]
The software center front end is free and open source. The code in the repository uses the API from openDesktop which as far as I'm aware is also free and open source.

http://socialdesktop.org/ocs/

**Comment by star-buck** [comment]
It is completely 100% libre software:
https://github.com/KDE/ocs-webserver
