### ISSUE TITLE
Does not run on Debian stable (10.4)

### ISSUE THREAD

**Issue by realmazharhussain** [Nitrux/nx-software-center#76]
**Issue**
It refuses to run on debian 10.4 saying "QObject: Cannot create children for a parent that is in a different thread."

**To Reproduce**
1. Go to AppImage's download directory
2. Make it executable and run it in terminal with ./Software_Center-x86_64.AppImage
3. It shows following error message on the screen instead of running the app

QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffeeedef610), parent's thread is QThread(0x24802f0), current thread is QThread(0x24ae5d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffeeedef610), parent's thread is QThread(0x24802f0), current thread is QThread(0x24ae5d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffeeedef610), parent's thread is QThread(0x24802f0), current thread is QThread(0x24ae5d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffeeedef610), parent's thread is QThread(0x24802f0), current thread is QThread(0x24ae5d0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffeeedef610), parent's thread is QThread(0x24802f0), current thread is QThread(0x24ae5d0)
org.kde.kwindowsystem: Could not find any platform plugin
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffeeedef610), parent's thread is QThread(0x24802f0), current thread is QThread(0x24ae5d0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
/tmp/.mount_Softwa0JTmHt/usr/bin/nx_software_center: symbol lookup error: /lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers

**My Desktop Setup:**
 - OS: Debian buster 10.4
 - CPU: Intel® Core™ i7-7500U CPU @ 2.70GHz × 4  - Version [e.g. 22]
 - Desktop: Gnome 3.30
 - Laptop: Dell Vostro 14-3468

**Comment by UriHerrera** [comment]
The AppImage in the release page and the source code in the master branch does not work. If you want to test, please use the branch `dev-mauikit-ui`.

**Comment by realmazharhussain** [comment]
If AppImage of release section does not work then please update it so that
it starts working.
And please give full information about compiling and installing it in
readme file.
