### ISSUE TITLE
App breaks after loading store contents

### ISSUE THREAD

**Issue by pktiuk** [Nitrux/nx-software-center#77]
**Describe the bug**
After screen with information: `Loading store contents...` app is closed.

Informations from terminal:
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffd52070620), parent's thread is QThread(0x1a1b060), current thread is QThread(0x1a5c8d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffd52070620), parent's thread is QThread(0x1a1b060), current thread is QThread(0x1a5c8d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffd52070620), parent's thread is QThread(0x1a1b060), current thread is QThread(0x1a5c8d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffd52070620), parent's thread is QThread(0x1a1b060), current thread is QThread(0x1a5c8d0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffd52070620), parent's thread is QThread(0x1a1b060), current thread is QThread(0x1a5c8d0)
org.kde.kwindowsystem: Could not find any platform plugin
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffd52070620), parent's thread is QThread(0x1a1b060), current thread is QThread(0x1a5c8d0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
qml: isWorking: true
qml: isReady: false
Both point size and pixel size set. Using pixel size.
qml: isWorking: true
qml: isReady: false
"addaps"  has no download link
"agora"  has no download link
"animashooter"  has no download link
...
"statusim"  has no download link

(process:54965): GLib-ERROR **: 16:59:13.429: Creating pipes for GWakeup: Too many opened files.
/tmp/.mount_SoftwauEC5o1/AppRun: line 6: 54965 breakpoint     (memory dump) ${APPDIR}/usr/bin/nx_software_center
```

**To Reproduce**
Run `./Software_Center-x86_64.AppImage`
**Expected behavior**
Load some apps and show them

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox

**Comment by leogama** [comment]
It's a "Too many opened files." error. The processes is keeping too many file descriptors open while downloading AppImage apps data from the sources (at least once for each app). The default limit for the number of open file descriptors of a processes is 1024 in Linux. So when the Software Center reaches this number, the kernel refuses to open the next pipe (don't know what it is for) and the process crashes.

Until this is fixed, a workaround is to create a small wrapper script to raise the limit to a number a bit larger. You can edit the Software Center's .desktop file in `~/.local/share/applications/`:
```ini
Exec=sh -c 'ulimit -n 10000; exec /home/<USERNAME>/Applications/Software_Center-x86_64.AppImage'
```

Or create a small (executable) shell script in the same directory of the Software Center's AppImage:
```sh
#!/bin/sh
ulimit -n 10000
exec ./Applications/Software_Center-x86_64.AppImage
```

You'll probably be able to run any of them by double clicking in the file manager.

**Comment by UriHerrera** [comment]
Is this reproducible in the branch `dev-mauikit-ui`? Otherwise, I'll close this issue. The `master` branch does not work.

**Comment by UriHerrera** [comment]
New code available in `master`. Closing.
