### ISSUE TITLE
Appimage in Discover app?

### ISSUE THREAD

**Issue by Thatoo** [Nitrux/nx-software-center#78]
I've just install Nitrux and I wanted to install few apps. I went into the app called Discover, the only one I found.
There, I couldn't find appimage to install.
If I go into settings, flatpak and snap are mentioned but no appimage.
Where is this nx-software-center in Nitrux?

**Comment by UriHerrera** [comment]
This is the wrong repository to ask about additional backends for Plasma Discover.
