### ISSUE TITLE
NX Software Center doesn't work

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#84]
**Describe the bug**
The NX Software Center doesn't launch.

**To Reproduce**
1. Update NX Software Center to version 0.0.8.
2. Click the launcher.
3. Nothing happens.

**Expected behavior**
NX Software Center opens.

This is the error log.

```
QFileSystemWatcher::addPaths: list is empty
kf.coreaddons: no metadata found in "/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/applications.so" "Failed to extract plugin meta data from '/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/applications.so'"
kf.coreaddons: no metadata found in "/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/desktop.so" "Failed to extract plugin meta data from '/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/desktop.so'"
Cyclic dependency detected between "file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/controls/Style.qml" and "file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/controls/Style.qml"
QQmlApplicationEngine failed to load component
qrc:/main.qml:26:9: Cannot assign to non-existent property "altHeader"
Lets remove MauiApp singleton instance
```

**Comment by probal31** [comment]
Hi,

I also faced some similar issue today.

You can try to build and install the mauikit and imagetools from main and try to launch nx sc again.

**Comment by UriHerrera** [comment]
Ah that's why, it needs MauiKit from main.

**Comment by star-buck** [comment]
Isnt that shipped in the appimage, so it runs everywhere fine?

**Comment by UriHerrera** [comment]
@star-buck Do you mean the AppImage in the Releases tab? That file is made from the old code. There's an open issue about updating it, see https://github.com/Nitrux/nx-software-center/issues/63.

**Comment by star-buck** [comment]
Not possible to do a new appimage? Kind of ironic, to have an apoimage
store not as appimage...

**Comment by UriHerrera** [comment]
Updated AppImage available in [Releases](https://github.com/Nitrux/nx-software-center/releases) tab.
