### ISSUE TITLE
Downloaded AppImages are not executable by default

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#87]
**Describe the bug**
Using the AppImage from the Releases tab, downloading AppImages is successful; however, the files are not executable by default.

When launching the software center from the terminal, the following error is displayed.

```
kf.service.services: KApplicationTrader: mimetype "x-scheme-handler/file" not found
```

 In the image below, I've download Etcher, Index, and CPU-X from the software center but only Index and Etcher show thumbnails (both in Index itself and the software center) because I manually added execution permissions to the files.

**To Reproduce**
1. Download AppImage from https://github.com/Nitrux/nx-software-center/releases/tag/latest.
2. Launch software center.
3. Download an app and launch it.
4. Nothing happens.

**Expected behavior**
The app launches.

**Screenshots**
![VirtualBox_Calculate Linux_17_09_2021_22_32_18](https://user-images.githubusercontent.com/3053525/133871205-171ed675-13e9-41cc-b0fe-dc44a0a8c8c7.png)

**Desktop (please complete the following information):**
 - Calculate Linux

**Comment by milohr** [comment]
NX SC 1.0.1?
MauiKit-FileBrowsing 2.0.2?

**Comment by milohr** [comment]
https://github.com/Nitrux/nx-software-center/commit/8f8901bcad4018766d0d4a89375fc10338d22168

I fixed a bug that was preventing the appimage integration. The integration step takes care of making the appimage executable. needs to be reviewed.

**Comment by milohr** [comment]
Fixed
