### ISSUE TITLE
Reduce the size of the AppImage

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-software-center#88]
The AppImage available in the Releases tab has a size of 181 MB, and according to the build logs, it's because there are many packages included in the bundle when appimage-builder creates the file.

appimage-builder allows excluding unwanted packages packages.

```
   exclude:
      - adwaita-icon-theme
      - appmenu-gtk-module-common
      - appmenu-gtk2-module
      ...
```

**Comment by milohr** [comment]
I have removed the dependency to MauiKit-ImageTools, which would end up including a huge database of cities and countries for GPS geolocation, and deps to exiv2 etc... which are not needed at all.
This could help to reduce the final size of the AppImage,

https://github.com/Nitrux/nx-software-center/commit/c35098b1e74b405d8400a53dbf992f938aeabddf

**Comment by milohr** [comment]
UPDATE: 
@UriHerrera managed to reduce the size down to 64 Mb.

**Comment by milohr** [comment]
With more care the size can be reduce even more. Previous recipes were including nonsense packages like bash and the whole kf5 libraries, which shows lack of commitment to make a good packing and demo appimages.

**Comment by star-buck** [comment]
64 MB is good. For average internet speeds, this is nothing, like 6 MB 10
years ago. For cases where jnternet is bad, apoimage and otger container
apps are the wrongconcept anyway, then even downloading a normal iso of 2GB
is a problem.

**Comment by UriHerrera** [comment]
The final size is 68 MB as of the latest commit and build.

![imagen](https://user-images.githubusercontent.com/3053525/134473483-f16a270e-c7dd-438b-9174-a11e876b6f10.png)

**Comment by probonopd** [comment]
Thank you very much. Much better now! :+1:
