### ISSUE TITLE
NX Software Center AppImage Does not run on Debian 10

### ISSUE THREAD

**Issue by faveoled** [Nitrux/nx-software-center#99]
/tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libappimage.so.1.0)
    /tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5)
    /tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5)
    /tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libQt5Core.so.5)
    /tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libQt5Core.so.5)
    /tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libQt5Xml.so.5)
    /tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libQt5Xml.so.5)
    /tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5)
    /tmp/.mount_nx-sofSWy88o//usr/bin/nx-software-center: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_nx-sofSWy88o//usr/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5)

**Comment by azubieta** [comment]
Which glibc version are do you have installed ? You can run `/lib/x86_64-linux-gnu/libc.so.6` to know it.

**Comment by faveoled** [comment]
GNU C Library (Debian GLIBC 2.28-10) stable release version 2.28.
    Copyright (C) 2018 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.
    There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
    PARTICULAR PURPOSE.
    Compiled by GNU CC version 8.3.0.
    libc ABIs: UNIQUE IFUNC ABSOLUTE
    For bug reporting instructions, please see:
    <http://www.debian.org/Bugs/>.

**Comment by coffseducation** [comment]
It will not launch on Kubuntu 23.04 either.

**Comment by UriHerrera** [comment]
The latest AppImage works in Debian 12.

![VirtualBox_Debian_25_06_2023_08_57_26](https://github.com/Nitrux/nx-software-center/assets/3053525/7901da60-f48f-4084-bf4d-378c604ec808)
